import Head from "next/head";
import Image from "next/image";
import Button from "../components/controls/Button";
import Categories from "../components/sections/Home/Categories";
import Featured from "../components/sections/Home/Featured";
import Landing from "../components/sections/Home/Landing";
import OnSale from "../components/sections/Home/OnSale";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      <Categories />
      <Featured />
      <OnSale />
    </div>
  );
}
